### PR TITLE
chore:  Add some hello world examples

### LINKED ISSUE #203: 2.15 not compiling with Typescript
Repro steps (from empty directory):

```bash
npm init
npm install @hpcc-js/wasm
npm install typescript
node_modules/.bin/tsc --init # Create the tsconfig.json
# Configure "moduleResolution": "Node16" in tsconfig.json as per instructions in homepage.
```

Then write the following `test.ts`:
```typescript
import { Graphviz } from "@hpcc-js/wasm/graphviz";

async function render() {
  const graphviz = await Graphviz.load();
  console.log(graphviz.dot('digraph G { Hello -> World }'));
}

render();
```

And now run it:
```bash
$ node_modules/.bin/tsc test.ts 
test.ts:1:26 - error TS2307: Cannot find module '@hpcc-js/wasm/graphviz' or its corresponding type declarations.

1 import { Graphviz } from "@hpcc-js/wasm/graphviz";
                           ~~~~~~~~~~~~~~~~~~~~~~~~
```

I'm using npm 9.6.7 and node v18.17.1.
npm installed typescript 5.3.2 and @hpcc-js/wasm 2.15.0.

### PR DESCRIPTION
**Pull request by GordonSmith**
Fixes #203

### CODE REVIEW

**Comment by rubenlg** [comment]
I tried the commonJS version, and here is the output:
```bash
npm install # OK
npm run build # OK
node index.js

node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /tmp/hpcc-js-wasm/examples/typescript/hello-world/commonjs/node_modules/@hpcc-js/wasm/dist/index.umd.js from /tmp/hpcc-js-wasm/examples/typescript/hello-world/commonjs/index.js not supported.
index.umd.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename index.umd.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /tmp/hpcc-js-wasm/examples/typescript/hello-world/commonjs/node_modules/@hpcc-js/wasm/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at /tmp/hpcc-js-wasm/examples/typescript/hello-world/commonjs/index.js:36:78 {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.17.1
```

**Comment by rubenlg** [comment]
To follow up, I upgraded nodejs to v20 and got the same error.

**Comment by GordonSmith** [comment]
@rubenlg - I just released v2.15.1 and I believe the following code should work as expected in TS + CommonJS:

```
const { Graphviz } = require("@hpcc-js/wasm/graphviz");

async function render() {
    const graphviz = await Graphviz.load();
    console.log(graphviz.dot('digraph G { Hello -> World }'));
}

render();
```

**Comment by rubenlg** [comment]
Now the CommonJS example in this PR works. I had to install the nodejs types on top of what's included in the package.json:
```
npm install --save-dev @types/node
```
I'll test my project and let you know, but this is very promising!

**Comment by rubenlg** [comment]
It's working! Typings get erased by using require, but it works, and my code using graphviz isn't that complex that losing types is a big deal.

Thanks!!

**Comment by GordonSmith** [comment]
FYI The following should also work:

```
import { Graphviz } from "@hpcc-js/wasm";

async function render() {
    const graphviz = await Graphviz.load();
    console.log(graphviz.dot('digraph G { Hello -> World }'));
}

render();
```

**Comment by rubenlg** [comment]
The second approach for some reason crashes Electron. I couldn't find why, even enabling debugging flags. However, I found this workaround works and has correct types:

```typescript
import type {Graphviz as GraphvizNS} from '@hpcc-js/wasm';
const Graphviz: typeof GraphvizNS = require("@hpcc-js/wasm/graphviz").Graphviz;
```

**Comment by GordonSmith** [comment]
...nice workaround for Electron...

**Comment by rubenlg** [comment]
Thanks a lot @GordonSmith !!

**Pull request merged**
