### PR TITLE
feat(GraphViz): Add basic error handling

### PR DESCRIPTION
**Pull request by GordonSmith**
Signed-off-by: Gordon Smith <gordonjsmith@gmail.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@magjac please review (not 100% if my tests are correct)

**Comment by magjac** [comment]
Works as expected. Thanks.

**Comment by GordonSmith** [comment]
(redoing test launcher) once travis passes I will pull

**Comment by GordonSmith** [comment]
Added test for blank svg and removed all refs to karma.

**Pull request merged**
