### PR TITLE
chore(build):  Add missing dependencies and updated build instructions

### PR DESCRIPTION
**Pull request by GordonSmith**
Signed-off-by: Gordon Smith <gordonjsmith@gmail.com>

### CODE REVIEW

**Comment by GordonSmith** [comment]
@magjac please review

**Comment by magjac** [comment]
I'm not sure I understand the **Note**. It works if you have the prerequisites already installed or run `sudo scripts/cpp-install-prerequisites.sh` before `npm run install-build-deps`, but as far as I can tell `npm run install-build-deps` doesn't apt install the prerequisites. But perhaps that's not what you mean. It's a bit unclear to me anyway.

**Comment by magjac** [comment]
The listed prerequisites were enough on one Ubuntu 18.04 computer which I had not installed myself, but on another one which recently installed Ubuntu 18.04 from scratch I also has to:
```
sudo apt-get install autoconf
sudo apt-get install bison
sudo apt-get install libtool
sudo apt-get install flex
```

**Comment by GordonSmith** [comment]
@magjac tweaked readme and added missing deps - if you can re-review.
Once approved, I will do a new release...

**Comment by magjac** [comment]
I think it would be better if the API Reference stated that the asynchronous versions returns a promise and the synchronous versions returns a string. As it is now it seems that each individual function might return either one and you have to check what you get.

**Comment by GordonSmith** [comment]
@magjac - tweaked as suggested (and added extra comments to Hello World example)

**Comment by magjac** [comment]
The graphvizSync asynchrounous function does not return an instance of graphviz, it returns a promise that resolves to an instance of graphviz (or how you best describe it).

**Comment by magjac** [comment]
A surplus backslash: in `Promise\<GraphvizSync>`. Otherwise it's good to go.

(Sorry for being picky. I mean well :slightly_smiling_face:).

**Comment by GordonSmith** [comment]
@magjac Picky is good!  Removed slash and once the tests complete ok will pull and publish.

**Pull request merged**
