### PR TITLE
feat:  Add support for Node JS

### PR DESCRIPTION
**Pull request by GordonSmith**
Refactor tests so they can run from browser and NodeJS

Signed-off-by: Gordon Smith <GordonJSmith@gmail.com>

### CODE REVIEW

**Comment by meoyawn** [comment]
just tried pulling `1.0.0` and got 

```
error - ./node_modules/@hpcc-js/wasm/dist/index.es6.js:2:0
Module not found: Can't resolve 'fs'
null
```

when trying to run this on Next.js

**Comment by GordonSmith** [comment]
Hmmm sounds like the es6 is leaking a conditional NodeJS requirement...

You can work around it with the following:  https://github.com/vercel/next.js/issues/7755 but I will investigate my end to see if I can clean it up as well...

**Comment by meoyawn** [comment]
image

also a weird thing on `0.3.15`: importing a (supposedly) simple wasm wrapper pulls 425kB of JS. I'm very new to JS modules but maybe this includes webpack polyfilling node modules like `fs`...

**Comment by meoyawn** [comment]
though my editor plugin is probably wrong https://bundlephobia.com/result?p=@hpcc-js/wasm@1.0.0

**Comment by GordonSmith** [comment]
You can also see the individual file sizes here:  https://cdn.jsdelivr.net/npm/@hpcc-js/wasm@1.0.0/dist/ 

The index.min.js is probably the most accurate.

**Comment by GordonSmith** [comment]
@meoyawn I just released 1.0.1 which should fix your issue (if you can verify that would be appreciated).

**Comment by meoyawn** [comment]
@GordonSmith can confirm `1.0.1` works with next.js, thanks!

**Pull request merged**
